[project]
name = "startup-os-ai-advisor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "numpy<2.0.0",
    "fastembed>=0.8.0",
    "notion-client>=3.1.0",
    "openai>=2.47.0",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "tiktoken>=0.13.0",
    "tqdm>=4.69.0",
    "sentence-transformers>=5.6.1",
    "streamlit>=1.61.1",
]
