apiVersion: 1

datasources:
  - name: StartupOS_PostgreSQL
    type: postgres
    uid: startup_os_pg
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: startup_os
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
